name: Java CI with Maven

on:
  push:
    branches: [ version5 ]
  pull_request:
    branches: [ version5 ]

jobs:
  # sonar:
  #   name: Sonar Cloud
  #   runs-on: ubuntu-latest

  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Set up JDK 8
  #     uses: actions/setup-java@v1
  #     with:
  #       java-version: 1.8
  #   - uses: actions/cache@v1
  #     with:
  #       path: ~/.m2/repository
  #       key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
  #       restore-keys: ${{ runner.os }}-maven-
  #   - name: Running Sonar
  #     run: mvn -B package sonar:sonar --file pom.xml
  #     env:
  #       SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
               
  test:
    name: Test - Dynamic test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-maven-
    - name: Maven Build
      run: mvn -B package -DskipTests
    - name: Maven Verify
      run: mvn -B verify 
     
     
#  artifact:
#    name: GitHub Package
#    runs-on: ubuntu-latest
#    needs: [test]

#    steps:
#    - uses: actions/checkout@v2
#    - name: Set up JDK 1.8
#      uses: actions/setup-java@v1
#      with:
#        java-version: 1.8
#    - name: artifact on GitHub Packages
#      run:  mvn -B clean deploy -DskipTests
#      env: 
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
